# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Backward compatibility
Naming/FileName:
  Exclude:
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'

# Backward compatibility
Naming/MethodName:
  Exclude:
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Autologin.rb'
    - 'src/modules/Pam.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'

# Disable as it is too bug prone to enable it
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'src/modules/Autologin.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: predicate, comparison
Style/NilComparison:
  Exclude:
    - 'src/modules/Autologin.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'test/nsswitch_test.rb'
