# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# Backward compatibility
Naming/FileName:
  Exclude:
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'

# Backward compatibility
Naming/MethodName:
  Exclude:
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Autologin.rb'
    - 'src/modules/Pam.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Rakefile'
    - 'src/lib/cfa/nsswitch.rb'
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'
    - 'test/cfa/nsswitch_test.rb'
    - 'test/nsswitch_test.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'src/lib/cfa/nsswitch.rb'

# Offense count: 43
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'src/modules/Autologin.rb'
    - 'src/modules/Nsswitch.rb'
    - 'src/modules/Pam.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'src/modules/Autologin.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: predicate, comparison
Style/NilComparison:
  Exclude:
    - 'src/modules/Autologin.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'test/nsswitch_test.rb'
